name: Playwright Tests
on:
  schedule:
    - cron:"0 0,12 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test

      # ✅ Upload artifacts for backup (optional)
      - name: Upload Monocart report
        uses: actions/upload-artifact@v4
        with:
          name: monocart-report
          path: monocart-report/

      # ✅ Deploy Monocart report to GitHub Pages
      - name: Deploy Monocart Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: monocart-report
          publish_branch: gh-pages
